export const SET_APPOINTMENTS = 'SET_APPOINTMENTS';
export const SET_ACTIVE_APPOINTMENT = 'SET_ACTIVE_APPOINTMENT';
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const CLEAR_APPOINTMENTS = 'CLEAR_APPOINTMENTS';
export const COMPLETE_APPOINTMENT = 'COMPLETE_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
